"""empty message

Revision ID: 0e11c22117f0
Revises: 6bf15e0de685
Create Date: 2019-07-23 15:14:07.509501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e11c22117f0'
down_revision = '6bf15e0de685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('time_booking', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking', 'time_booking')
    # ### end Alembic commands ###
