"""empty message

Revision ID: 18689f1d3636
Revises: b256ee0f7a0c
Create Date: 2019-07-23 12:23:00.699487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18689f1d3636'
down_revision = 'b256ee0f7a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('parking', 'c')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('c', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('parking', 'status')
    # ### end Alembic commands ###
