"""empty message

Revision ID: 30a5527e37ed
Revises: fd4f0ab6bae6
Create Date: 2019-07-23 21:13:54.202998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a5527e37ed'
down_revision = 'fd4f0ab6bae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
