"""empty message

Revision ID: 57753368c586
Revises: 5a7a5c1ab14e
Create Date: 2019-07-26 11:03:20.799628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57753368c586'
down_revision = '5a7a5c1ab14e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('in_use_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking', 'in_use_status')
    # ### end Alembic commands ###
