"""empty message

Revision ID: 993ba021afbe
Revises: 0e11c22117f0
Create Date: 2019-07-23 20:14:54.327372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993ba021afbe'
down_revision = '0e11c22117f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
