"""empty message

Revision ID: 99bc193b19f4
Revises: bbd6289269e0
Create Date: 2019-07-24 10:27:55.091018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99bc193b19f4'
down_revision = 'bbd6289269e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parking', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parking', 'price')
    # ### end Alembic commands ###
