"""empty message

Revision ID: a8f0032da170
Revises: 99bc193b19f4
Create Date: 2019-07-24 10:30:27.654814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f0032da170'
down_revision = '99bc193b19f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('transaction_price_fkey', 'transaction', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('transaction_price_fkey', 'transaction', 'price', ['price'], ['id'])
    # ### end Alembic commands ###
