"""empty message

Revision ID: a99282da6c03
Revises: 30a5527e37ed
Create Date: 2019-07-23 21:23:27.644904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a99282da6c03'
down_revision = '30a5527e37ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('transaction', 'time_lot',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.DateTime(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('transaction', 'time_lot',
    #            existing_type=sa.DateTime(),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)
    # ### end Alembic commands ###
    pass
