"""empty message

Revision ID: b256ee0f7a0c
Revises: 
Create Date: 2019-07-23 12:15:55.413912

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision = 'b256ee0f7a0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass


def downgrade():
   pass
