"""empty message

Revision ID: c5da706b2e1f
Revises: 7a6929cbc905
Create Date: 2019-07-30 10:47:59.022050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5da706b2e1f'
down_revision = '7a6929cbc905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('building', sa.Column('street_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('building', 'street_location')
    # ### end Alembic commands ###
