"""empty message

Revision ID: fabc3aefe5e8
Revises: bc427695ab73
Create Date: 2019-07-27 00:28:09.911063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fabc3aefe5e8'
down_revision = 'bc427695ab73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ticket_qrcode', sa.String(), nullable=True))
    op.drop_column('transaction', 'ticket_qrode')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('ticket_qrode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transaction', 'ticket_qrcode')
    # ### end Alembic commands ###
