"""empty message

Revision ID: fd4f0ab6bae6
Revises: 993ba021afbe
Create Date: 2019-07-23 20:28:34.475451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4f0ab6bae6'
down_revision = '993ba021afbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###
